task_name: 'sea'
conv_manager: 'visibility'

global_variable:
  date: 'August 15, 2024, Monday'
  date_after_three: 'August 18, 2024, Thursday'
  client_name: 'Mr. Steve Jordan'
  OVERDUE_DATE: 'Auguest 10, 2024'
  LOAN_AMOUNT: '2000 dollars'
  Max_PTP_DATE: 'August 25, 2024'
  relationship_json_example1: {"relationship":"sister of the client"}
  relationship_json_example2: {"relationship":"friend of the client"}
  repay_date_method_json_example: {"repay_date":"August 3, 2024", "repay_amount": "200 dollars", "repay_method":"by APP"}
  can_not_repay_reason_json_example1: {"reason":"no money"}
  can_not_repay_reason_json_example2: {"reason": "the client is in hospital."}
  repay_date_json_example: {"repay_date": "August 25, 2024"}

entry_node: 0

unclear_trigger_prompt : "if the situation is not any of the above cases, output {target}"

prompt_dir: './prompts/gene_script_less_node_prompts/'

llm:
  - llm_type: 'azure'
    client_parameters:
      api_key_name: "AZURE_gpt4o_eastjp"
      api_version: '2024-06-01'
      azure_endpoint: "https://openai-sea-japan.openai.azure.com/"

node_config:
  - node_index: 0
    node_name: 'greetings'
    node_type: 'multi_2ask'
    support_global: false
    support_other: false
    first_message: ['Hello, I am a representative from NXMoney. Am I speaking with {client_name}?', 'Hello, I am a representative from NXMoney. Is this {client_name}?']
    first_message_first: true
    assistant_name: 'Susan'
    client_name: 'client'
    pathways:
      A: 1
      B: 2
      C: 3
      D: 4
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.3
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    visible_lines: 0
    no_transfer_target: 'E'

  - node_index: 1
    node_name: 'AskForPayment'
    node_type: 'multi_2ask'
    support_global: false
    support_other: false
    first_message: null
    first_message_first: false
    assistant_name: 'Susan'
    client_name: 'client'
    pathways:
      A: 5
      B: 6
      C: 7
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.3
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    visible_lines: 0
    no_transfer_target: 'D'

  - node_index: 5
    node_name: 'AskForReason'
    node_type: 'multi_2ask'
    support_global: false
    support_other: false
    first_message: null
    first_message_first: false
    assistant_name: 'Susan'
    client_name: 'client'
    pathways:
      A: 14
      B: 8
      C: 9
      D: 15
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.3
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    visible_lines: 0
    no_transfer_target: 'E'

  - node_index: 14
    node_name: 'AskForPayment2'
    node_type: 'multi_2ask'
    support_global: false
    support_other: false
    first_message: null
    first_message_first: false
    assistant_name: 'Susan'
    client_name: 'client'
    pathways:
      A: 7
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
      - temperature: 0.3
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    visible_lines: 0
    no_transfer_target: 'B'

  - node_index: 2
    node_name: 'wrong_number'
    node_type: 'end_call'
    end_message: "I'm sorry to bother you, Good Bye."
    pathways:
      A: 24

  - node_index: 3
    node_name: 'relative/friend'
    node_type: 'end_call'
    end_message: "I'm sorry to bother you, but please remind {client_name} to make the payment on time."
    pathways:
      A: 10

  - node_index: 4
    node_name: 'busy'
    node_type: 'end_call'
    end_message: "Sorry for the interruption, but please inform {client_name} to pay the NXMoney bill as soon as possible. We will be in touch again. Bye."
    pathways:
      A: 24

  - node_index: 6
    node_name: 'alreadPaid'
    node_type: 'end_call'
    end_message: "Okay, we will check our record, goodbye."
    pathways:
      A: 24

  - node_index: 7
    node_name: 'AgreeToPay'
    node_type: 'end_call'
    end_message: "ok. Please remember to complete the payment on time. If you have any issue, please contact our staff."
    pathways:
      A: 11

  - node_index: 8
    node_name: 'BetterToPay'
    node_type: 'end_call'
    end_message: "I need to remind you that late payments will require additional interest charges. Perhaps a payment plan would be more suitable for you. Stay in touch. Goodbye."
    pathways:
      A: 12
  
  - node_index: 9
    node_name: 'sympathy'
    node_type: 'end_call'
    end_message: "I understand that you had financial difficulties because of what happened. I will first note in the system the reason for the delay. If you ever have the funds to settle earlier, you can maintain your good credit record. I'm hoping you'll be okay soon."
    pathways:
      A: 12
  
  - node_index: 15
    node_name: 'pay_date_after_three'
    node_type: 'end_call'
    end_message: "Ok, please be sure to make the payment on that day. Good bye."
    pathways:
      A: 13

  - node_index: 10
    node_name: 'retrieve-relationship'
    node_type: 'retrieval'
    retrieved_name : 'relationship'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 11
    node_name: 'retrieve-payment'
    node_type: 'retrieval'
    retrieved_name : 'payment'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 12
    node_name: 'retrieve-reason'
    node_type: 'retrieval'
    retrieved_name : 'reason_of_no_payment'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 13
    node_name: 'retrieve-date'
    node_type: 'retrieval'
    retrieved_name : 'date_of_payment'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 24
    node_name: 'end-session'
    node_type: 'end_session'

global_node: null
