task_name: 'sea'
conv_manager: 'visibility'

global_variable:
  language: Chinese
  date: 'August 2, 2024. Monday'
  client_name: '张建国先生'
  OVERDUE_DATE: '2024年7月30号'
  LOAN_AMOUNT: '2000元'
  Max_PTP_DATE: '2024年8月10号'
  name_relationship_json_example1: {"name":"张小飞", "relationship":"客户的妹妹"}
  name_relationship_json_example2: {"name":"未提供", "relationship":"客户的朋友"}
  repay_date_method_json_example: {"repay_date":"2024年8月1号", "repay_method":"通过APP"}
  partial_repayment_json_example: {"repay_date":"2024年8月3号", "repay_method":"通过银行转账", "repay_amount":"500元"}

node_type_valid_for_global_node:
  - 'single'
  - 'multi'
  - 'multi_2ask'
  - 'instant'

entry_node: 0

unclear_trigger_prompt : "if the situation is not any of the above cases, output {target}"

prompt_dir: './prompts/sea_script_prompts_chinese/'

llm:
  - llm_type: 'azure'
    client_parameters:
      api_key_name: "AZURE_gpt4o_eastjp"
      api_version: '2024-06-01'
      azure_endpoint: "https://openai-sea-japan.openai.azure.com/"

node_config:
  - node_index: 0
    node_name: '0'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: ['早上好，请问是{client_name}吗？', '你好，是{client_name}吗？']
    first_message_first: true
    assistant_name: 'customer service'
    client_name: 'client'
    pathways:
      A: 1
      B: 4
      C: 3
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    visible_lines: 0

  - node_index: 1
    node_name: '1'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: '我确认一下，是{client_name}对吗？'
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 4
      C: 11
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 2
    node_name: '2'
    node_type: 'end_call'
    end_message: "抱歉，我们复查一下。谢谢你，再见！"
    pathways:
      A: 24
  
  - node_index: 3
    node_name: '3'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "啊，只需要两三分钟，可以吗？"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 7
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 4
    node_name: '4'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: '对不起，请问你认识{client_name}吗？'
    assistant_name: 'customer service'
    pathways:
      A: 8
      B: 2
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 6
    node_name: '6'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "你好。您的SeaMoney账户已于 {OVERDUE_DATE}到期，金额为 {LOAN_AMOUNT}。现在可以付款吗？"
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 14
      D: 15
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 7
    node_name: '7'
    node_type: 'end_call'
    end_message: "了解了。我们将在其他时间再次与您联系。谢谢！"
    pathways:
      A: 24

  - node_index: 8
    node_name: '8'
    node_type: 'end_call'
    end_message: "好的，谢谢。我们会再联系他。再见！"
    pathways:
      A: 9
  
  - node_index: 9
    node_name: '9'
    node_type: 'retrieval'
    retrieved_name : 'name_and_relationship'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 256
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 10
    node_name: '10'
    node_type: 'end_call'
    end_message: "啊很抱歉。请您检查Shopee 应用程序中的 SeaMoney 帐户。再见。"
    pathways:
      A: 24

  - node_index: 11
    node_name: '11'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "啊，只需要两三分钟，可以吗？"
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 10
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 12
    node_name: '12'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: '谢谢，您将使用什么付款方式？'
    assistant_name: 'customer service'
    pathways:
      A: 19
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
    
  - node_index: 13
    node_name: '13'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "好的，我记录一下。您何时向 SeaMoney 付款？"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 17
      C: 20
      D: 21
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'
  
  - node_index: 14
    node_name: '14'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: '我明白。请问您无法付款的原因是什么？'
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 22
      B: 21
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 15
    node_name: '15'
    node_type: 'end_call'
    end_message: '好的，请耐心等待我们处理你的付款，谢谢。'
    pathways:
      A: 24
  
  - node_index: 16
    node_name: '16'
    node_type: 'end_call'
    end_message: '好的。请您在 {repay_date}、{repay_method} 支付 {LOAN_AMOUNT}。请您务必遵守。'
    pathways:
      A: 24

  - node_index: 17
    node_name: '17'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "好的，但您的帐户仍然会被冻结。您将使用什么付款方式进行付款？"
    assistant_name: 'customer service'
    pathways:
      A: 26
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 18
    node_name: '18'
    node_type: 'end_call'
    end_message: "谢谢。那请在 {repay_date}{repay_method} 向 SeaMoney 支付的金额为 {repay_amount}。"
    pathways:
      A: 24

  - node_index: 19
    node_name: '19'
    node_type: 'retrieval'
    retrieved_name : 'method_of_payment'
    pathways:
      'A': 16
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 256
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 20
    node_name: '20'
    node_type: 'end_call'
    end_message: '谢谢。我们只能将您的帐户延期至 {Max_PTP_DATE}。如有问题请联系我们。'
    pathways:
      A: 24
  
  - node_index: 21
    node_name: '21'
    node_type: 'end_call'
    end_message: "我了解您的困难。请保持良好的信用记录。我希望你很快就会好起来。"
    pathways:
      A: 24

  - node_index: 22
    node_name: '22'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "我明白。您可能会被收取滞纳金。是否可以想办法还款？"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 20
      D: 23
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 23
    node_name: '23'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: '我明白。具体什么日期可以付款？'
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 14
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.0
        stream: true
        max_tokens: 256
    conversation:
      visible_node_list: 'all'

  - node_index: 26
    node_name: '26'
    node_type: 'retrieval'
    retrieved_name : 'method_of_partial_payment'
    assistant_name: 'customer service'
    pathways:
      'A': 18
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 256
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 24
    node_name: '24'
    node_type: 'end_session'

global_node: null
  # node_index: 25
  # node_name: '25'
  # node_type: 'global'
  # condition_target: 'A'
  # trigger_prompt: "if the client has questions about the company and has not been answered, output {target}"
  # assistant_name: 'customer service'
  # system_prompt_paths:
  #   - '/condition_sys.txt'
  #   - '/mission_sys.txt'
  # user_prompt_paths:
  #   - '/condition_user.txt'
  # llm_ids: 
  #   - 'gpt-4o'
  #   - 'gpt-4o'
  # llm_ask_parameters:
  #   - temperature: 0.0
  #     stream: false
  #     max_tokens: 1
  #   - temperature: 0.0
  #     stream: true
  # conversation:
  #   visible_node_list: 'all'