task_name: 'sea'
conv_manager: 'visibility'

global_variable:
  date: 'July 29, 2024. Monday'
  client_name: 'Mr. Steve Jordan'
  OVERDUE_DATE: 'July 22, 2024'
  LOAN_AMOUNT: '2000 dollars'
  Max_PTP_DATE: 'August 10, 2024'
  name_relationship_json_example1: {"name":"Susan Jordan", "relationship":"sister of the client"}
  name_relationship_json_example2: {"name":"Not provided", "relationship":"friend of the client"}
  repay_date_method_json_example: {"repay_date":"August 3, 2024", "repay_method":"by APP"}
  partial_repayment_json_example: {"repay_date":"August 3, 2024", "repay_method":"by bank transfer", "repay_amount":"500 dollars"}

node_type_valid_for_global_node:
  - 'single'
  - 'multi'
  - 'multi_2ask'
  - 'instant'

entry_node: 0
global_end_node: 30
internal_steps_limit: 4

unclear_trigger_prompt : "if the situation is not any of the above cases, output {target}"

prompt_dir: './prompts/sea_script_prompts/'

llm:
  - llm_type: 'azure'
    client_parameters:
      api_key_name: "AZURE_gpt4o_eastjp"
      api_version: '2024-06-01'
      azure_endpoint: "https://openai-sea-japan.openai.azure.com/"

node_config:
  - node_index: 0
    node_name: '0'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: ['Hello! Good morning! Am I speaking with {client_name}?', 'Hello! Is this {client_name}?']
    first_message_first: true
    assistant_name: 'customer service'
    client_name: 'client'
    pathways:
      A: 1
      B: 4
      C: 3
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    visible_lines: 0
    max_round: 10
    default_transfer: 1

  - node_index: 1
    node_name: '1'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: 'Just to reconfirm, is this {client_name}?'
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 4
      C: 11
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 6

  - node_index: 2
    node_name: '2'
    node_type: 'end_call'
    end_message: "Sorry for the inconvenience, we'll double check our records for this. Thank you and have a nice day!"
    pathways:
      A: 24
  
  - node_index: 3
    node_name: '3'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "Ah, okay, it's just a quick call for about 2-3 minutes. Can we talk now?"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 7
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 6

  - node_index: 4
    node_name: '4'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: 'Sorry, do you know {client_name}?'
    assistant_name: 'customer service'
    pathways:
      A: 8
      B: 2
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 8

  - node_index: 6
    node_name: '6'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "I'm Susan from SeaMoney. I just advise that this call is being recorded for quality purposes. This is regarding your SeaMoney account that was due on {OVERDUE_DATE} amounting to {LOAN_AMOUNT} as of today. Can it be paid now?"
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 14
      D: 15
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 3
    default_transfer: 12

  - node_index: 7
    node_name: '7'
    node_type: 'end_call'
    end_message: "I see. We'll get back in touch with you at another time. Thanks, and have a great day!"
    pathways:
      A: 24

  - node_index: 8
    node_name: '8'
    node_type: 'end_call'
    end_message: "Okay, thank you for letting me know. We'll try to get in touch with him at another time. Thanks, and have a great day!"
    pathways:
      A: 9
  
  - node_index: 9
    node_name: '9'
    node_type: 'retrieval'
    retrieved_name : 'name_and_relationship'
    assistant_name : 'customer service'
    client_name : 'person'
    pathways:
      'A': 24
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 10
    node_name: '10'
    node_type: 'end_call'
    end_message: "Ah, I'm sorry for the inconvenience, I'm just reminding you to check your Shopee app for your SeaMoney account."
    pathways:
      A: 24

  - node_index: 11
    node_name: '11'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "Ah, okay, it's just a quick call for about 2-3 minutes. Can we talk now?"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 6
      B: 10
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 6

  - node_index: 12
    node_name: '12'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: 'Glad to hear that you can pay now. What method of payment will you use to settle?'
    assistant_name: 'customer service'
    pathways:
      A: 19
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 19

  - node_index: 13
    node_name: '13'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "Alright, I'll just take notes one by one. When will you pay with SeaMoney?"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 17
      C: 20
      D: 21
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 12

  - node_index: 14
    node_name: '14'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: 'I understand. May I know what is the reason why you have not been able to pay?'
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 22
      B: 21
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 22

  - node_index: 15
    node_name: '15'
    node_type: 'end_call'
    end_message: 'Great to hear that, and noted on this. Just wait for us to post the payment, sorry for the inconvenience.'
    pathways:
      A: 24
  
  - node_index: 16
    node_name: '16'
    node_type: 'end_call'
    end_message: 'Thank you for that information. Let me recap our agreement. You will pay {repay_date}, {repay_method} amounting to {LOAN_AMOUNT}. Please make sure that you can comply with this agreement in order to maintain the good credit standing of your account. For further questions, kindly send a message through our live chat or email.'
    pathways:
      A: 24

  - node_index: 17
    node_name: '17'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "That's great to hear, but I'm just informing you that it's still possible to receive a call and your account is still frozen since you haven't fully paid yet. What method of payment will you use to settle?"
    assistant_name: 'customer service'
    pathways:
      A: 26
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 26

  - node_index: 18
    node_name: '18'
    node_type: 'end_call'
    end_message: 'Thank you for that information. Let me recap our agreement. Please pay SeaMoney for {repay_date}, {repay_method} amounting to {repay_amount}.'
    pathways:
      A: 24

  - node_index: 19
    node_name: '19'
    node_type: 'retrieval'
    retrieved_name : 'method_of_payment'
    pathways:
      'A': 16
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 16

  - node_index: 20
    node_name: '20'
    node_type: 'end_call'
    end_message: 'Thank you for that information. Unfortunately, we can only extend your account until {Max_PTP_DATE}. Just find a way to settle by then. I just advise that you will still receive a call from us as part of our collections process. For further questions, kindly send a message through our live chat or email.'
    pathways:
      A: 24
  
  - node_index: 21
    node_name: '21'
    node_type: 'end_call'
    end_message: "I understand that you had financial difficulties because of what happened. I will first note in the system the reason for the delay. If you ever have the funds to settle earlier, you can maintain your good credit record. I'm hoping you'll be okay soon."
    pathways:
      A: 24

  - node_index: 22
    node_name: '22'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: "I understand, but it would be much better for you to settle the account. Your SeaMoney accounts are still frozen, and it is possible that you will be charged late fees. Is it possible to make a way to repay?"
    first_message_first: true
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 20
      D: 23
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 12

  - node_index: 23
    node_name: '23'
    node_type: 'multi_2ask'
    support_global: false
    support_other: true
    first_message: 'I understand. What specific date can it be paid?'
    assistant_name: 'customer service'
    pathways:
      A: 12
      B: 13
      C: 14
      D: 23
    system_prompt_paths:
      - '/pathway_sys.txt'
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/pathway_user.txt'
    llm_ids: 
      - 'gpt-4o'
      - 'gpt-4o'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        max_tokens: 1
        logit_bias:
          32: 100
          33: 100
          34: 100
          35: 100
          36: 100
      - temperature: 0.0
        stream: true
    conversation:
      visible_node_list: 'all'
    max_round: 10
    default_transfer: 12

  - node_index: 26
    node_name: '26'
    node_type: 'retrieval'
    retrieved_name : 'method_of_partial_payment'
    assistant_name: 'customer service'
    pathways:
      'A': 18
    llm_ids: 
      - 'gpt-4o'
    system_prompt_paths:
      - '/mission_sys.txt'
    user_prompt_paths:
      - '/mission_user.txt'
    llm_ask_parameters:
      - temperature: 0.0
        stream: false
        response_format: 
          type: "json_object"
    conversation:
      visible_node_list: 'all'

  - node_index: 30
    node_name: '30'
    node_type: 'end_call'
    end_message: 'Fatal error.'
    pathways:
      A: 24

  - node_index: 24
    node_name: '24'
    node_type: 'end_session'

global_node: null
  # node_index: 25
  # node_name: '25'
  # node_type: 'global'
  # condition_target: 'A'
  # trigger_prompt: "if the client has questions about the company and has not been answered, output {target}"
  # assistant_name: 'customer service'
  # system_prompt_paths:
  #   - '/condition_sys.txt'
  #   - '/mission_sys.txt'
  # user_prompt_paths:
  #   - '/condition_user.txt'
  # llm_ids: 
  #   - 'gpt-4o'
  #   - 'gpt-4o'
  # llm_ask_parameters:
  #   - temperature: 0.0
  #     stream: false
  #     max_tokens: 1
  #   - temperature: 0.0
  #     stream: true
  # conversation:
  #   visible_node_list: 'all'